### ISSUE TITLE
urllib3 related error "InsecurePlatformWarning: A true SSLContext object is not available"

### ISSUE THREAD

**Issue by ravijo** [buntyke/TRo2017#1]
This error is not directly related to the code. However it can be seen while trying to update `jupyter`. Below is the error message:

```
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/appdirs-1.4.0.dist-info/METADATA'
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

**Workaround:**

It seems that `urllib3` is creating some blockage while `jupyter` is trying to update itself. Removing `urllib3` doesn't help in this case. Below is the workaround:

`
pip install appdirs --upgrade
`

**Comment by buntyke** [comment]
Thank you for this issue! I updated the troubleshooting section with this information.
