### ISSUE TITLE
No module named tabulate

### ISSUE THREAD

**Issue by ravijo** [buntyke/TRo2017#3]
`from tabulate import tabulate`

is showing following error:

`No module named tabulate`

**Workaround**
Use following command to install tabulate

`sudo pip install tabulate`

**Comment by buntyke** [comment]
The package tabulate is from legacy code and is not used here. I have removed all references for tabulate from the source code and this need not be installed. Please check this [commit](https://github.com/buntyke/TRo2017/commit/76331bda7e8b7a1975f6fc6aedc6d873392bb590).
